---
- name: Backup Proxmox VM before upgrade
  hosts: pve-node
  become: yes
  tasks:
    - name: Display start message
      debug:
        msg: "Starting backup of VM 3023 before upgrade..."

    - name: Run vzdump to back up VM
      command: >
        vzdump 3023 --storage NVME2 --mode snapshot --compress zstd
      register: backup_result

    - name: Show backup output
      debug:
        msg: "{{ backup_result.stdout }}"

    - name: Display completion message
      debug:
        msg: "Backup completed for VM 3023. Ready for upgrade."
