---
- name: Move files in Ansible Semaphore
  hosts: localhost
  tasks:
    - name: Ensure the source directory exists
      stat:
        path: /mnt/pve/NVME2
      register: dump_dir

    - name: Move dump files if the directory exists
      shell: mv /mnt/pve/NVME2/dump/* /mnt/pve/SYN0LOGY-NFS/dump/
      when: dump_dir.stat.exists
