- name: Start STD1-BR-FGT 101
  ansible.builtin.command: qm start 101
  register: STD1-BR-FGT_101
  changed_when: "'started' in STD1-BR-FGT_101.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD1-HQ-SERVER 102
  ansible.builtin.command: qm start 102
  register: STD1-HQ-SERVER_102
  changed_when: "'started' in STD1-HQ-SERVER_102.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD1-HQ-FGT 103
  ansible.builtin.command: qm start 103
  register: STD1-HQ-FGT_103
  changed_when: "'started' in STD1-HQ-FGT_103.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD1-BR-CLIENT 104
  ansible.builtin.command: qm start 104
  register: STD1-BR-CLIENT_104
  changed_when: "'started' in STD1-BR-CLIENT_104.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD2-HQ-CLIENT 105
  ansible.builtin.command: qm start 105
  register: STD2-HQ-CLIENT_105
  changed_when: "'started' in STD2-HQ-CLIENT_105.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD2-HQ-SERVER 106
  ansible.builtin.command: qm start 106
  register: STD2-HQ-SERVER_106
  changed_when: "'started' in STD2-HQ-SERVER_106.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD2-HQ-FGT 107
  ansible.builtin.command: qm start 107
  register: STD2-HQ-FGT_107
  changed_when: "'started' in STD2-HQ-FGT_107.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD2-BR-FGT 108
  ansible.builtin.command: qm start 108
  register: STD2-BR-FGT_108
  changed_when: "'started' in STD2-BR-FGT_108.stdout"

- name: Wait for 10 seconds before starting the next VM
  ansible.builtin.pause:
    seconds: 10

- name: Start STD2-BR-CLIENT 109
  ansible.builtin.command: qm start 109
  register: STD2-BR-CLIENT_109
  changed_when: "'started' in STD2-BR-CLIENT_109.stdout"

- name: Display Results
  ansible.builtin.debug:
    msg:
      {% for i in range(101, 145) %}
      - "VM {{ lookup('vars', 'STD' + ((i - 100) // 5 + 1)|string + '-' + ['HQ-CLIENT', 'HQ-SERVER', 'HQ-FGT', 'BR-FGT', 'BR-CLIENT'][((i - 100) % 5)] + '_' + i|string) }}: {{ lookup('vars', 'STD' + ((i - 100) // 5 + 1)|string + '-' + ['HQ-CLIENT', 'HQ-SERVER', 'HQ-FGT', 'BR-FGT', 'BR-CLIENT'][((i - 100) % 5)] + '_' + i|string + '.stdout') }}"
      {% endfor %}
